/**
 * GENERATED by `node scripts/gen-module-art.mjs` from
 * client/public/images/modules/manifest.json. Do not edit by hand; rerun it.
 * `client/src/lib/moduleImages.test.ts` fails while this disagrees with the
 * manifest or with the files on disk.
 */
export const BUNDLED_MODULE_ART: Readonly<Record<string, string>> = {
  "automation": "automation.webp",
  "badges": "badges.webp",
  "commerce": "commerce.webp",
  "crowdpool": "crowdpool.webp",
  "events": "events.webp",
  "exchange": "exchange.webp",
  "feed": "feed.webp",
  "forum": "forum.webp",
  "governance": "governance.webp",
  "gratitude": "gratitude.webp",
  "health": "health.webp",
  "hypha": "hypha.webp",
  "introductions": "introductions.webp",
  "library": "library.webp",
  "map": "map.webp",
  "messaging": "messaging.webp",
  "network": "network.webp",
  "profiles": "profiles.webp",
  "progression": "progression.webp",
  "quests": "quests.webp",
  "resources": "resources.webp",
  "stays": "stays.webp",
  "tools": "tools.webp",
};
