/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  GAME CONFIG — THE WHITE-LABEL SWAP POINT
 * ─────────────────────────────────────────────────────────────────────────────
 *  This file holds the PLATFORM's defaults for everything project-specific.
 *  Every village runs the same code from the same repository, so whatever is
 *  written here becomes thirteen villages' default at once.
 *
 *  DO NOT EDIT THIS FILE TO STAND UP A VILLAGE. It used to say the opposite,
 *  in three numbered steps, and it was wrong on all three: nobody forks this
 *  repository (docs/ARCHITECTURE.md, "a fork inherits the platform by
 *  pulling, not by find-and-replace"), the CSS theme tokens are set live from
 *  Admin, and `data/*-seed.json` has not been the seed path since the seeds
 *  moved to `server/seeds/`. A founder following those steps would have been
 *  hand-editing shared platform code for values that a wizard sets in a
 *  browser, and every one of those edits would be lost at the next pull.
 *
 *  Where a village's own identity goes instead: Admin, Make This Yours. It
 *  writes the `brand` DOCUMENT IN `app_config`, read through
 *  `dbDocument(getPool(), "brand", ...)` in `server/index.ts`, which
 *  `mergedConfig()` layers OVER this file and serves at `/api/game/config`.
 *  A blank field here inherits nothing and shows nothing, which is the
 *  correct behaviour for a slot no village has filled.
 *  docs/PROVISIONING.md step 7 is the walkthrough.
 *
 *  THIS PARAGRAPH SAID `data/brand.json` UNTIL 2026-09-03 AND THERE IS NO
 *  SUCH FILE. There is no `data/` directory in this repository and no code
 *  anywhere reads a brand file from disk: the overlay has been a database
 *  row for as long as the Setup Wizard has existed. The wrong name sent at
 *  least one session looking for a file to edit, which is the same failure
 *  the three numbered steps above caused, so it is corrected here rather
 *  than left as a small inaccuracy in a header everybody reads first.
 *
 *  WHAT THIS FILE IS FOR, then: the neutral fallback a village sees before
 *  its founder has set anything, and the platform-level game design (the
 *  stage ladder, the path definitions, season cadence semantics) that a
 *  re-skin is not supposed to change. `scripts/check-identity-keys.mjs`
 *  guards the first of those and fails if any identity slot here starts
 *  carrying one village's name.
 *
 *  Nothing in server logic or client components should hardcode the project
 *  name, the currency name, the member name, or the stage ladder. They all
 *  read from here, through `mergedConfig()`. A village name found outside
 *  this file (and outside the seeds, and outside the brochure pages
 *  `scripts/check-brand-refs.mjs` lists as SHOPFRONT) is a platform bug.
 * ─────────────────────────────────────────────────────────────────────────────
 */

// ── Types (platform-level, do not edit per project) ──────────────────────────

export interface GamePath {
  id: string;
  label: string;
  /** Short noun for what this persona contributes */
  role: string;
  route: string;
}

/**
 * An on-chain token the platform DISPLAYS but does not control. The address and
 * chain identify it on Base; balances are read through a public RPC and shown on
 * profiles and the economics section. Hypha remains the source of truth for the
 * value itself. Empty `address` means "not deployed yet, show nothing".
 */
export interface TokenRef {
  /** Display symbol, e.g. "EQUITY" or "VOICE". */
  symbol: string;
  /** Human name, e.g. "Village Equity". */
  name: string;
  /** ERC-20 contract address on Base, or "" until deployed. */
  address: string;
  /** Chain id. Base mainnet is 8453. */
  chainId: number;
  /** Token decimals, for formatting balances. */
  decimals: number;
}

export type StageRule =
  | { type: "default" }                       // everyone starts here
  | { type: "account" }                       // has created an account
  | { type: "training-complete" }             // finished all training modules
  | { type: "membership" }                    // signed the membership covenant
  | { type: "quests"; min: number }           // N consented quest completions
  | { type: "granted" };                      // manually granted by the team

export interface GameStage {
  id: string;
  name: string;
  description: string;
  /** How this stage is earned. "granted" stages are set by the team in Admin. */
  rule: StageRule;
  /** Multiplier applied to the monthly gratitude sending budget. */
  gratitudeMultiplier: number;
}

export interface NextActionRule {
  id: string;
  /** Condition evaluated server-side against the player's game state. */
  when:
    | "no-training"
    | "no-membership"
    | "no-quest-claimed"
    | "quest-in-progress"
    | "gratitude-unspent"
    | "always";
  label: string;
  href: string;
}

export interface GameConfig {
  project: {
    name: string;
    tagline: string;
    /** What a committed member is called (e.g. Amora Family member, Citizen, Villager). */
    memberName: string;
    /**
     * WHAT THIS VILLAGE CALLS THE PEOPLE WHO RUN IT (Rye, 2026-09-03).
     *
     * A LABEL AND NOTHING ELSE. It is not a role, it is not a capability, and
     * nothing reads it to decide who may do what. `isAdmin` and the one
     * capability gate in `shared/capabilities.ts` are untouched by whatever a
     * village types here: the same people can do the same things, and the
     * member-facing copy says the village's own word for them instead of the
     * platform's. "Catalyst" is the default; a village that says founder,
     * steward or elder sets it in Admin, Make This Yours.
     *
     * Singular, capitalised, and it takes an article in a sentence ("a
     * Catalyst can close it"). `client/src/lib/gameApi.ts` holds the article
     * rule so one heuristic serves every render site.
     *
     * It sits in this plane, the brand overlay, because it answers "whose
     * village is this and what does it call things", which is the same
     * question as `memberName` beside it. `shared/gameVariables.ts` is the
     * plane for behaviour, and nothing about this changes any behaviour.
     */
    catalystName: string;
    location: string;
    /** ISO 3166 alpha-2 country the project lives in (0083, P8). Blank means
     *  unsaid, and money display falls back to the universal CHF default. */
    country: string;
    /** ISO 4217 currency the project counts in (Amora: CRC). DISPLAY only:
     *  Stripe settlement and the ledger never read this. */
    fiatCurrency: string;
    adminPath: string;
    /** The project's OUTSIDE website. Blank hides every "Main Site" link —
     *  a fork with no external site shows no link rather than a dead one. */
    siteUrl: string;
    /** Optional events page. Blank hides the footer Events link. */
    eventsUrl: string;
    /** Where a visitor's business or investment enquiry should go. Blank hides
     *  every "email us" control on the shopfront pages rather than sending a
     *  stranger's enquiry to whichever address happened to be compiled in.
     *  This is a PUBLIC role address: it renders into the page as a mailto
     *  link and is served by /api/game/config, so never a personal inbox. */
    contactEmail: string;
    /** The one-sentence footer introduction under the logo. */
    footerBlurb: string;
  };
  currency: {
    /** The in-site recognition currency (e.g. Gratitude, Seeds, Thanks).
     *  Earned from consented quests, sent peer to peer, settled on lunar cycles.
     *  Platform-governed. This is NOT the equity token, even when a project
     *  wants to brand its equity "Gratitude" too: keep them separate here. */
    name: string;
    /** Sentence-position variant, e.g. "gratitude" in "send gratitude". */
    nameLower: string;
    /** The project's EQUITY token, on Base, governed by Hypha. The platform
     *  never mints, moves, or prices it: it reads balances and displays them. */
    equity: TokenRef;
    /** Governance-weight token, on Base, also Hypha-governed. Read-only here. */
    voice: TokenRef;
  };
  /** Hero images rendered by React pages. Runtime-swappable via the brand overlay
   * (the Setup Wizard). og:image and favicon are build-time in index.html, not here. */
  images: {
    hero: string;
    investorHero: string;
    residentHero: string;
    stewardHero: string;
    prosperityHero: string;
    masterPlanHero: string;
    /** Header logo (on the primary-colour nav). ~64px tall, width auto. */
    logo: string;
    /** Footer/secondary mark. ~90px tall, width auto. */
    heartLogo: string;
    /** Browser tab icon, swapped in client-side once config loads. */
    favicon: string;
    /*
     * ALT TEXT, one optional key per image above.
     *
     * The Setup Wizard has collected these nine values since it shipped, and
     * `PUT /api/admin/brand` blind-spread them into storage, so a founder typed
     * a description, saved, reloaded the wizard and saw it come back. Nothing
     * else in the system knew the keys existed: `mergedConfig()` REBUILDS
     * `images` from named keys, so every one was dropped before
     * `/api/game/config` serialized, and no `img alt` read them. A labelled
     * accessibility control that discards what a founder types is worse than
     * no control, because it also records the work as done.
     *
     * Optional on purpose. An absent value inherits the platform default alt
     * text at the render site; an empty string is a deliberate "this image is
     * decorative" and is passed through as one.
     *
     * EIGHT keys, not nine. `favicon` is a `<link rel="icon">`, never an
     * `<img>`, and a browser tab icon is named by the page title: there is no
     * attribute for alt text to become. The wizard says so where the field
     * used to be, because offering the control and dropping the value is the
     * failure this block exists to end.
     */
    heroAlt?: string;
    investorHeroAlt?: string;
    residentHeroAlt?: string;
    stewardHeroAlt?: string;
    prosperityHeroAlt?: string;
    masterPlanHeroAlt?: string;
    logoAlt?: string;
    heartLogoAlt?: string;
  };
  paths: GamePath[];
  /** The progression ladder, in order. First stage is the default. */
  stages: GameStage[];
  gratitude: {
    /** Base sending budget per calendar-month cycle (before stage multiplier). */
    monthlyBudget: number;
    /** Max sends to the same recipient per cycle. */
    maxPerRecipientPerCycle: number;
    /** A message is required with every acknowledgment. */
    requireMessage: boolean;
  };
  /** Ordered: the first matching rule becomes the player's next-best-action. */
  nextActions: NextActionRule[];
  season: SeasonConfig;
}

/** One season. `endsOn` is the turn date: the day this season hands over to the
 *  next one (so it belongs to the next season, not this one). */
export interface SeasonEntry {
  id: string;
  name: string;
  theme: string;
  focus: string;
  startsOn: string; // ISO date, inclusive
  /** ISO date, exclusive, the day the season turns. EMPTY means open-ended:
   *  it runs until somebody starts the next one, which is what a founding
   *  season does. */
  endsOn: string;
  /**
   * The season PATTERN this season runs (0050): which circles, seats, badges
   * and quests are live while it is current. Empty means the season carries
   * no pattern, which is every village that has not opted in, and nothing
   * about their structure changes at a turn.
   */
  patternId?: string;
  /** What this season is actually trying to achieve. Shown on the banner//season. */
  goals: { text: string; done: boolean }[];
}

export interface SeasonConfig {
  /** Seed values for data/season.json — editable in Admin after first boot.
   *  Seasons are a LIST so the server can pick the current one by date. A single
   *  season with a passed end date is how a banner silently starts lying. */
  seasons: SeasonEntry[];
  /** How this project paces its seasons. Drives the "queue next season" helper;
   *  projects differ (quarters, solstices, lunar cycles). */
  cadence: "quarterly" | "solstice-equinox" | "lunar" | "custom";
  /** IANA zone the season turns in — a season turn is a ritual moment, and UTC
   *  midnight is not midnight where the village lives. */
  timezone: string;
}

// ── PLATFORM DEFAULTS (every village inherits these until Admin overrides) ───
//
// The old header here read "AMORA CONFIGURATION (edit below for a new
// project)", which named one village and invited the next founder to edit
// shared code. Both halves were wrong. See the file header.

export const GAME_CONFIG: GameConfig = {
  project: {
    name: "Unnamed Village",
    // The founder's words for what this platform is for (Rye, 2026-08-31),
    // and a sentence that belongs to no village in particular: every project
    // standing one of these up is doing some version of it. The string it
    // replaced ("Co-Become the Most Beautiful Village") was one village's
    // slogan, and it is one of the three strings the brand guard structurally
    // cannot see, because it carries no village's name to match on. Sentence
    // case, as he wrote it.
    tagline: "healing the land and ourselves, together",
    memberName: "Village member",
    // The platform's own word, belonging to no village, so it is a NEUTRAL
    // value in `scripts/check-identity-keys.mjs` rather than a pending one.
    // A village renames it in Admin and every member-facing sentence that
    // names an admin follows.
    catalystName: "Catalyst",
    // Empty on purpose: there is no neutral location. A village sets its own
    // in Admin, Make This Yours. Graduated out of the identity guard's pending
    // list on 2026-09-03, AFTER confirming the live village stores its own
    // ("Dominicalito, Costa Rica", read from app_config.brand), which is the
    // ordering the 2026-08-31 outage exists to enforce.
    location: "",
    // GRADUATED OUT OF KNOWN_PENDING on 2026-09-02, and it is the one of the
    // four that could be graduated without waiting on the founder, because
    // NOTHING READS IT. Measured, not assumed: the only occurrences of this
    // key in the whole of server/, shared/ and client/src/ are the empty
    // scaffold at server/index.ts:1019, the overlay merge at
    // server/index.ts:2733, and `defaultDisplayCurrency` in shared/money.ts,
    // which accepts `country` in its signature and never reads it in its body
    // (it branches on fiatCurrency alone and falls back to CHF). No page
    // renders it, no export carries it, no fallback stands on it.
    //
    // So this is not the 2026-08-31 outage shape. That outage was a value
    // being taken OUT of the defaults while a live deployment was still
    // RENDERING it from here and held no copy of its own. Here there is
    // nothing rendering to take away: blanking it changes no pixel on any
    // village, and it stops one country code from being thirteen villages'
    // declared country. A founder who wants theirs recorded sets it in Admin,
    // Make This Yours, exactly as before.
    //
    // If a future feature starts reading this key, that feature is what makes
    // it renderable again, and it inherits the blank rather than Costa Rica.
    country: "",
    fiatCurrency: "CRC",
    adminPath: "/admin",
    // Blank on purpose, same pattern as the hero images and the header/footer
    // marks below: Layout.tsx and Quests.tsx already render these links only
    // when truthy ({siteUrl && (...)}), so a fresh instance with no outside
    // site or events page shows no dead or wrong-owner link rather than one
    // pointing at the first village that shipped from this codebase.
    //
    // contactEmail follows the same rule and matters more, because its failure
    // is silent: a compiled-in address takes a visitor's enquiry, sends it to
    // somebody else's inbox, and shows the visitor a normal mail composer. No
    // error, and the founder never learns the lead existed. Blank hides the
    // control (useVillageLinks in client/src/lib/gameApi.ts).
    siteUrl: "",
    eventsUrl: "",
    contactEmail: "",
    // Was "A regenerative village in Costa Rica where all beings belong and
    // thrive." Every village that never edited its footer told visitors it was
    // in Costa Rica. Same graduation and same precondition as `location`: the
    // live village holds its own copy, so neutralising this cannot blank it.
    footerBlurb: "A regenerative village where all beings belong and thrive.",
  },

  currency: {
    /*
     * "GRATITUDE" IS THE DEFAULT, AND THE FOUNDER SETTLED IT.
     *
     * A lane changed this to "Recognition" on 2026-08-31 and its reasoning was
     * good: one village runs a mechanic called Gratitude, and shipping that
     * village's word as every fork's default looked like the same mistake as
     * shipping its tagline.
     *
     * It was reverted, because the premise was wrong and the premise was mine.
     * The founder had reported that the Setup Wizard confused him about WHICH
     * token he was renaming, and I turned that symptom report into a rename
     * task. Asked directly, he described the model and named this one:
     *
     *   "the name for the token that every member gets at the beginning of
     *    every lunar cycle and distributes that token to recognize other
     *    people for that cycle is called gratitude and that's the default. Of
     *    course every project can rename this on their own"
     *
     * So Gratitude is the platform's word for this mechanic, not one village's
     * borrowed vocabulary, and a village that runs something else renames it in
     * Admin then Tokens.
     *
     * NOT "Village Credits". That is already the name of the OTHER currency:
     * the token gratitude.pool_token names by default (drizzle/0007), which is
     * the pool the cycle distributes across recognition. Both names appear in
     * one sentence on the quest board, so two names that collide make that
     * sentence unreadable. shared/currencyDefaults.test.ts pins it shut.
     *
     * THE SLUG DOES NOT MOVE. "gratitude" stays this token's slug forever:
     * every ledger row is keyed to it and a slug is history's identity. Only
     * the display name is the village's own word.
     *
     * WHAT THIS DEFAULT REACHES, AND WHAT IT DOES NOT. The Setup Wizard prints
     * it under the field as "Platform default: ...", and mergedConfig() falls
     * back to it when nothing else holds a name. It does NOT decide what a
     * brand-new village's members read: drizzle/0006 seeds tokens.name for
     * this slug and the token registry WINS over both this value and the brand
     * overlay. That was measured against a freshly migrated database, not
     * reasoned about.
     */
    name: "Gratitude",
    /** Derived, not independent: mergedConfig() computes name.toLowerCase()
     *  and reaches this stored value only when the name is empty. Held in
     *  agreement with name by shared/currencyDefaults.test.ts. */
    nameLower: "gratitude",
    // Platform-neutral defaults. A project's real token names and symbols are
    // its own identity (Amora calls its equity token "Amora" per the
    // project's wish); that belongs in the project's own fork of this file,
    // not in the platform default every fork inherits. Addresses are blank
    // until the tokens deploy; the economics section shows nothing rather
    // than a fake balance meanwhile.
    equity: { symbol: "EQUITY", name: "Village Equity", address: "", chainId: 8453, decimals: 18 },
    voice: { symbol: "VOICE", name: "Village Voice", address: "", chainId: 8453, decimals: 18 },
  },

  images: {
    /*
     * THE SIX HERO SLOTS SHIP EMPTY, AND THAT IS THE FIX.
     *
     * They used to hold six URLs on one village's WordPress site. Two things
     * were wrong with that and only one of them was visible.
     *
     * The visible one: every last URL now answers 404 while the host root
     * answers 200, so the live homepage, the four journey pages and the master
     * plan all render torn images with their alt text spilling out of the card.
     * Measured 2026-08-29, six URLs, six 404s.
     *
     * The one that would still be wrong if they came back: a fork pulling this
     * platform inherits somebody else's private domain as the source of its own
     * artwork, with no way to make it its own. That is the same shape as the
     * seat holders and the appraisal figure, and re-pointing at a working URL
     * on the same host would fix the broken pictures and leave the fork problem
     * exactly where it was.
     *
     * Empty means "this village has not added its art yet", which every
     * consumer already understands: `Image` draws a quiet mark and keeps the
     * alt text as its accessible name, and the Setup Wizard's Pictures step
     * writes a real URL or an upload into the brand overlay above this.
     */
    hero: "",
    investorHero: "",
    residentHero: "",
    stewardHero: "",
    prosperityHero: "",
    masterPlanHero: "",
    // Same "ship empty" fix as the six hero slots above, for the same two
    // reasons: the old Amora URLs point at a private domain a fork cannot
    // make its own, and (for logo/heartLogo specifically) no ship-ready
    // neutral mark exists to put here instead - inventing one would just be
    // a different brand welded into platform code. Blank is handled: Layout
    // renders an empty spacer in place of the header logo and simply omits
    // the footer mark, and the Setup Wizard's Pictures step is where a
    // village uploads its own into the brand overlay above this.
    //
    // favicon is the one exception with a real answer: client/index.html
    // already ships a neutral platform mark
    // (/assets/images/platform-favicon.svg) as the static default, and
    // /manifest.webmanifest and App.tsx's client-side swap both already fall
    // back to it when this field is blank. So blank here is not a gap, it is
    // what makes that fallback engage instead of being permanently shadowed
    // by a non-empty default.
    logo: "",
    heartLogo: "",
    favicon: "",
  },

  paths: [
    { id: "investor", label: "Investor", role: "Capital Contributor", route: "/investor" },
    { id: "steward", label: "Village Steward", role: "Co-Creator", route: "/steward" },
    { id: "resident", label: "Resident", role: "Co-Creator", route: "/resident" },
    { id: "prosperity-creator", label: "Prosperity Creator", role: "Business Builder", route: "/prosperity" },
  ],

  // Amora's Path of Growth (from the Game Guide). Stages are earned by real
  // acts, never abstract points. "granted" stages are recognized by the team.
  stages: [
    { id: "visitor", name: "Visitor", description: "Discovering what this village is.", rule: { type: "default" }, gratitudeMultiplier: 0 },
    { id: "guest", name: "Guest", description: "Created a profile and stepped inside.", rule: { type: "account" }, gratitudeMultiplier: 1 },
    { id: "immersant", name: "Immersant", description: "Spent immersive time with the community.", rule: { type: "granted" }, gratitudeMultiplier: 1 },
    { id: "participant", name: "Participant", description: "Completed community training.", rule: { type: "training-complete" }, gratitudeMultiplier: 1 },
    { id: "member", name: "Member", description: "Signed the Love Letter and joined the community.", rule: { type: "membership" }, gratitudeMultiplier: 2 },
    { id: "contributor", name: "Contributor", description: "Completed a first quest for the village.", rule: { type: "quests", min: 1 }, gratitudeMultiplier: 2 },
    { id: "quest-seeker", name: "Quest Seeker", description: "Contributing steadily through quests.", rule: { type: "quests", min: 3 }, gratitudeMultiplier: 2 },
    { id: "initiate", name: "Initiate", description: "Walking the Co-Creator Right of Passage.", rule: { type: "granted" }, gratitudeMultiplier: 2 },
    { id: "co-creator", name: "Co-Creator", description: "Consented by the Co-Creators circle.", rule: { type: "granted" }, gratitudeMultiplier: 3 },
    { id: "role-holder", name: "Role Holder", description: "Holding a seasonal role for the village.", rule: { type: "granted" }, gratitudeMultiplier: 3 },
    { id: "guide", name: "Guide", description: "Seven or more years of stewardship.", rule: { type: "granted" }, gratitudeMultiplier: 4 },
    { id: "sage", name: "Sage", description: "Twenty-one or more years of stewardship.", rule: { type: "granted" }, gratitudeMultiplier: 5 },
  ],

  gratitude: {
    monthlyBudget: 100,
    maxPerRecipientPerCycle: 1,
    requireMessage: true,
  },

  nextActions: [
    { id: "training", when: "no-training", label: "Continue your community training", href: "/training" },
    { id: "membership", when: "no-membership", label: "Sign the Love Letter", href: "/love-letter" },
    { id: "first-quest", when: "no-quest-claimed", label: "Claim your first quest", href: "/quests" },
    { id: "finish-quest", when: "quest-in-progress", label: "Finish your active quest", href: "/quests" },
    { id: "send-gratitude", when: "gratitude-unspent", label: "Send gratitude to someone this month", href: "/gratitude" },
    { id: "explore", when: "always", label: "Explore open quests", href: "/quests" },
  ],

  season: {
    cadence: "solstice-equinox",
    timezone: "America/Costa_Rica",
    seasons: [
      {
        id: "foundations-2026",
        name: "Season of Foundations",
        theme: "Building and Preparing",
        focus: "Site planning, first structures, and growing the founding community.",
        startsOn: "2026-06-21",
        endsOn: "2026-09-22",
        goals: [
          { text: "Master plan reviewed and agreed", done: false },
          { text: "First homes designed and costed", done: false },
          { text: "Founding circle fully assembled", done: false },
        ],
      },
      {
        id: "rooting-2026",
        name: "Season of Rooting",
        theme: "Planting and Deepening",
        focus: "First builds underway, food forests planted, and the circles finding their rhythm.",
        startsOn: "2026-09-22",
        endsOn: "2026-12-21",
        goals: [
          { text: "Ground broken on the first structures", done: false },
          { text: "Food forest phase one planted", done: false },
        ],
      },
    ],
  },
};

/** Convenience: look up a stage by id, with the default stage as fallback. */
export function getStage(id: string | null | undefined): GameStage {
  return GAME_CONFIG.stages.find((s) => s.id === id) ?? GAME_CONFIG.stages[0];
}

/** Stage index for ordering comparisons (later stages have higher index). */
export function stageIndex(id: string): number {
  return GAME_CONFIG.stages.findIndex((s) => s.id === id);
}

/**
 * The answer from `claimPaths`. `paths` is undefined when the caller sent no
 * `paths` key at all, which means "leave my paths alone" and is not an error.
 */
export type PathClaim =
  | { ok: true; paths: string[] | undefined }
  | { ok: false; error: string };

/**
 * VALIDATE A SUBMITTED PATH LIST. Paths are an enum on the wire, and the one
 * route a member can reach used to write whatever JSON arrived: a bare string,
 * an object, an array of ids nothing has ever defined. Registration already
 * demanded an array, so the door a member could open twice a day was the
 * looser of the two.
 *
 * `held` is the member's CURRENT list, and every id in it stays claimable even
 * when this build's config no longer names it. A village that renames or
 * retires a path would otherwise lock every member holding the old id out of
 * the control completely: their own stored value would fail validation and
 * take the whole request down with it, including the part that drops the dead
 * id. The profile states the same rule for rendering, where an id this build
 * does not know is read and never dropped. Dropping stays possible either way,
 * because dropping means leaving the id out of the array.
 *
 * Duplicates collapse and order is the caller's. Nothing reads path order, so
 * echoing back what was sent is what makes a round trip legible.
 *
 * `held` is typed `unknown` and checked rather than trusted, because the rows
 * this guard exists to stop already exist. The unvalidated route wrote a bare
 * string and an object into that column for as long as it stood, the users
 * repo's `fromJsonCol` returns whatever JSON it finds without asking for an
 * array, and a `held.map` on one of those would answer a member's first claim
 * with a 500. A stored value that is not a list of ids adds nothing to the
 * claimable set, which leaves the member able to claim anything on offer.
 */
export function claimPaths(input: unknown, held: unknown = []): PathClaim {
  if (input === undefined) return { ok: true, paths: undefined };
  if (!Array.isArray(input)) return { ok: false, error: "Paths must be a list of path ids" };
  const claimable = new Set<string>([
    ...GAME_CONFIG.paths.map((p) => p.id),
    ...(Array.isArray(held) ? held.filter((p): p is string => typeof p === "string") : []),
  ]);
  const paths: string[] = [];
  for (const raw of input) {
    if (typeof raw !== "string") return { ok: false, error: "Every path is named by its id" };
    if (!claimable.has(raw)) return { ok: false, error: `No such path: ${raw}` };
    if (!paths.includes(raw)) paths.push(raw);
  }
  return { ok: true, paths };
}
